### PR TITLE
Feature/update cpgf

### PR DESCRIPTION
**Pull request by svalaskevicius**

### CODE REVIEW

**Comment by svalaskevicius** [comment]
Hi @wqking,

I hope you're well.

I've updated cpgf version used in qtjs generator, and ported my previous fixes. Do you maybe want to review these commits and see if any of them can be imported to cpgf?

Please let me know if you have any questions regarding the PR.

Regards,
Sarunas

**Comment by wqking** [comment]
Hello,

Sorry for so late reply.
Thanks for the reminder. I will check to see if there is anything I can merge back.

**Comment by svalaskevicius** [comment]
Hi, 

No problem :) let me know if you have any questions / comments.

I am still thinking of an alternative solution to "reuse existing V8 object by ptr address" - just cannot think of any :) although in both cases its using GClassGlueDataPointer so maybe it could be used to validate as well - will return to it once I have a bit more time.

Regards,

**Comment by svalaskevicius** [comment]
Hi @wqking,

I was just looking at this code here: [qml.js](https://github.com/svalaskevicius/qtjs-generator/blob/d005b2a9ac7095fcca6c900cb4312a6b87059f51/examples/qml.js) and it looks slightly verbose :)

Do you think it would be a good idea to implement implicit param conversion based on class constructors? (i.e. same as in C++). This would allow to get rid of all those "new qt.QString()" and "new QVariant()" in the code.

Also, a feature to create custom conversion logic e.g. by template specialisation would be a great addition as well - it would allow to pass a js array instead of generating a "new qt.QStringList()" manually.

Would this feature break any existing functionality? it could (should?) be ranked even below the current conversion (base/deriv. class casting) to preserve the priorities.

Regards,
Sarunas

**Comment by wqking** [comment]
Hi,

1, Reusing object. I've done in current development version, not released yet.

2, Implicit conversion constructor. It sounds good but there are more problems than it seems. The biggest problem is, script languages don't have all the types which are in C++. For example, we can't distinguish between float and double in JavaScript.

So if we have C++ code

struct A { A(float); };
void func(A a);
void func(double d);

We may select wrong overload function.

3, Customized conversion. Sounds interesting. I will think about it.

**Comment by svalaskevicius** [comment]
hi, I am not sure its possible to create a stand-alone unit test for the segfault, however if you remove the line from [main.cpp](https://github.com/svalaskevicius/qtjs-generator/blob/feature/update-cpgf/src/runner/main.cpp#L61) it fails to clean it up properly later.

I've added it to be able to control when which services are being disposed. The stacktrace I get w/o the mentioned line is:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff799c693 in cpgf::ImplMetaTypedItem::doDestroyInstance (this=0x1b46e28, instance=0x1b4fb20) at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/src/gmetaapi.cpp:872
#2  0x00007ffff79a656d in cpgf::ImplMetaClass::destroyInstance (this=0x1b46e28, instance=0x1b4fb20) at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/src/gmetaapi.cpp:525
#3  0x00007ffff7a9502e in cpgf::(anonymous namespace)::GMetaObjectLifeManagerDefault::freeObject (this=0x1b97e90, object=0x1b4fb20, metaClass=0x1b46e68)
    at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/src/metatraits/gmetaobjectlifemanager.cpp:43
#4  0x00007ffff79d9bd2 in cpgf::bind_internal::GObjectInstance::~GObjectInstance (this=0x1b4fbc0, __in_chrg=<optimized out>)
    at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/src/scriptbind/gbindcommon.cpp:345
#5  0x00007ffff79e26d8 in cpgf::GSharedPointer<cpgf::bind_internal::GObjectInstance>::~GSharedPointer (this=0x1b4fb98, __in_chrg=<optimized out>)
    at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/build/../include/cpgf/gsharedptr.h:168
#6  0x00007ffff79da29f in cpgf::bind_internal::GObjectGlueData::~GObjectGlueData (this=0x1b4fb50, __in_chrg=<optimized out>)
    at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/src/scriptbind/gbindcommon.cpp:395
#7  0x00007ffff79da35e in cpgf::bind_internal::GObjectGlueData::~GObjectGlueData (this=0x1b4fb50, __in_chrg=<optimized out>)
    at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/src/scriptbind/gbindcommon.cpp:397
#8  0x00007ffff79e2a62 in cpgf::GSharedPointer<cpgf::bind_internal::GObjectGlueData>::~GSharedPointer (this=0x1b4fc98, __in_chrg=<optimized out>)
    at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/build/../include/cpgf/gsharedptr.h:168
#9  0x00007ffff7aee447 in cpgf::bind_internal::GGlueDataWrapperImplement<cpgf::GSharedPointer<cpgf::bind_internal::GObjectGlueData> >::~GGlueDataWrapperImplement (this=0x1b4fc90, 
    __in_chrg=<optimized out>) at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/src/scriptbind/../pinclude/gbindcommon.h:658
#10 0x00007ffff7aee4a6 in cpgf::bind_internal::GGlueDataWrapperImplement<cpgf::GSharedPointer<cpgf::bind_internal::GObjectGlueData> >::~GGlueDataWrapperImplement (this=0x1b4fc90, 
    __in_chrg=<optimized out>) at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/src/scriptbind/../pinclude/gbindcommon.h:658
#11 0x00007ffff79e1a4e in cpgf::bind_internal::freeGlueDataWrapper (p=0x1b4fc90) at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/src/scriptbind/../pinclude/gbindcommon.h:823
#12 0x00007ffff79db6ab in cpgf::bind_internal::GGlueDataWrapperPool::clear (this=0x1b38b60) at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/src/scriptbind/gbindcommon.cpp:619
#13 0x00007ffff79db4f7 in cpgf::bind_internal::GGlueDataWrapperPool::~GGlueDataWrapperPool (this=0x1b38b60, __in_chrg=<optimized out>)
    at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/src/scriptbind/gbindcommon.cpp:605
#14 0x00007ffff7aedfd5 in cpgf::GUninitializerDeleter<cpgf::bind_internal::GGlueDataWrapperPool>::operator() (this=0x1af22c8)
    at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/src/scriptbind/../pinclude/gstaticuninitializerorders.h:40
#15 0x00007ffff7aedf65 in cpgf::callback_internal::GCallbackGlobal_0<cpgf::GUninitializerDeleter<cpgf::bind_internal::GGlueDataWrapperPool>, void>::virtualInvoke (self=0x1af22c0)
    at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/build/../include/cpgf/private/gcallback_p.h:533
#16 0x00007ffff798d30f in cpgf::callback_internal::GCallbackAgent_0<void>::doInvoke<void> (this=0x1af22b8)
    at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/build/../include/cpgf/private/gcallback_p.h:533
#17 0x00007ffff798d1e5 in cpgf::callback_internal::GCallbackAgent_0<void>::operator() (this=0x1af22b8)
    at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/build/../include/cpgf/private/gcallback_p.h:533
#18 0x00007ffff798ad05 in cpgf::(anonymous namespace)::GOrderedStaticUninitializerManager::~GOrderedStaticUninitializerManager (this=0xa07cc0, __in_chrg=<optimized out>)
    at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/src/glifecycle.cpp:54
#19 0x00007ffff798bdef in cpgf::GScopedPointerDeleter_Delete<cpgf::{anonymous}::GOrderedStaticUninitializerManager>::Delete(cpgf::(anonymous namespace)::GOrderedStaticUninitializerManager *) (
    p=0xa07cc0) at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/build/../include/cpgf/gscopedptr.h:33
#20 0x00007ffff798b738 in cpgf::GScopedPointer<cpgf::{anonymous}::GOrderedStaticUninitializerManager, cpgf::GScopedPointerDeleter_Delete<cpgf::{anonymous}::GOrderedStaticUninitializerManager>, cpgf::GScopedPointerResetPredict<cpgf::{anonymous}::GOrderedStaticUninitializerManager> >::~GScopedPointer(void) (
    this=0x7ffff7dd8ea8 <cpgf::(anonymous namespace)::orderedStaticUninitializerManager>, __in_chrg=<optimized out>)
    at /home/sarunas/priv/dev/qtjs-generator/lib/cpgf/build/../include/cpgf/gscopedptr.h:69
#21 0x00007fffef8ac52a in __cxa_finalize (d=0x7ffff7dd6a00) at cxa_finalize.c:55
#22 0x00007ffff798a543 in __do_global_dtors_aux () from ../tools/../lib/cpgf/lib/libcpgf.so
#23 0x00007fffffffe050 in ?? ()
#24 0x00007ffff7de9f47 in _dl_fini () at dl-fini.c:253
Backtrace stopped: frame did not save the PC
```

**Comment by svalaskevicius** [comment]
Regarding your previous comment:

> 1, Reusing object. I've done in current development version, not released yet.

Thanks! Looking forward to see it :)

> 2, Implicit conversion constructor. It sounds good but there are more problems than it seems. The biggest problem is, script languages don't have all the types which are in C++. For example, we can't distinguish between float and double in JavaScript.
> 
> So if we have C++ code
> 
> struct A { A(float); };
> void func(A a);
> void func(double d);
> 
> We may select wrong overload function.

This should work if the implicit conversion would be the last prioritised step to check. i.e. it would only be checked in the cases where its currently failing that it cannot find method to call. (In your given example it would still try to use double directly and would not invoke A conversion at all).

I also understand this is really an additional feature (not of the highest priority :) ), and might also be changing javascript based programming paradigms and be unexpected for JS developers, although as we're already bringing c++ classes why not to use c++ based conversion logic?

I've currently changed my API to use const char \* instead of QString, and will see in future if I would ever need it again..

> 3, Customized conversion. Sounds interesting. I will think about it.

Thanks :) It would help to make the APIs nicer - although again, this feature is not of the highest priority and would be just "nice to have" :)

**Comment by svalaskevicius** [comment]
will merge the PR to the master branch.

we can still continue the discussion here as its relevant to the future updates :)

**Comment by wqking** [comment]
hi, I have implemented the customized converter in current development version, not released yet. However, seems I forgot mentioning one thing. In your current version, the fundamental types such as char, int, and their pointers counterpart, can be converted to objects implicitly, if there are implicit constructor. Maybe you can try it.

**Comment by svalaskevicius** [comment]
Hi @wqking,

How are you?

I've added a few more commits to cpgf, however they weren't a part of this pull request. Some of them general improvements and minor fixes, others - updating the supported V8 engine.

I'm pasting the filtered list of commits to cpgf (that are now also in the master branch of this project) accompanied with an extracted patch list (git format-patch) as a separate gist for convenience. Please can you review them and let me know your thoughts? 

## List of commits
- 70c15f405fb014763f56e24df35b9a082ea6532e allow accessing non virtual protected methods in wrapped classes
- 536b78fada5d71cd8389e513f38e2a128d4a9b2b enable operators for subclasses of templates
- 66de8bf5aa9b806d4a54d5c2fd5be92891be1415 enable more complex return types
- ec7ddf693ccc4f9ade4d1ac0ccb4478a13443ad7 fix cpgf class registration to module
- 6a4ea876abab2334ea5ce6faf1301805377090f7 fix v8/cpgf cleaning up sequence
- a666508b8074a653bea6f4b13c6be08064ee9458 link with node's v8
- d5f76f76ab394831c2067d22684a153240ce8631 upgrading v8
- e6a277764aea53dcc813f280858dbeda8bca9ccd upgrading v8
- b4a201860684a184cdadd9455b429349e92fb148 upgrading v8
- 099a0c7156245cb147aa3e3d4f6a36f9dd6e68cc upgrading v8
- 080a3ae470b0015ce02c746198c033f84f16e2b3 upgrading v8
- c0774e255a116367d5b04dc0c2d51dc2e4cf5f79 upgrading v8
- c6f57de7d25e1bb8c662904f21e313e2f967e645 upgrading v8
- d01478ada61dc69aa66bc403afdb1f0c01d6dd4c WIP: cpgf compatibility with new v8
- e25bd664f47d3fa0394e5e7ca9527e81948c53b7 swap construct order
- 321f4d2988771a231ec05547d554f20a03a8ad67 use nodes v8
- b690947e98459a86b10b9e557bcfd89afd384332 Merge branch 'master' into feature/nodejs
- 19b4a5b3255d27f030792036a9fa63d2798775c3 add possibility to specify transfer result ownership policy
- cd77bfddba625fefd0da4e8e5d867387594b95b3 inject v8 context to cpgf

## Patches

Please see this gist: https://gist.github.com/svalaskevicius/789a718a2ce31f2b4b8d

**Comment by wqking** [comment]
Hi,

I would say, the changes are great. Seems you have much deeper understanding of cpgf library now. Great work.
I will merge the changes back when I have time.

**Comment by svalaskevicius** [comment]
thanks! there are still a few more changes I am planning, however, will start focusing on fixing the tests, as upgrading v8 broke them :(

the few ideas are:
- optimise GMetaTypedItemList::findByType as currently it looks that the initialisation (fixupHierarchy) is O(n^2) while using a hash would be better, this would also affect the mapping of return type after every function call (haven't tried of benchmarked anything yet, but will try)
- allow introspecting cpgf classes in javascript (enumarating, so that I could console.log(<cpgf module or class>) to see its contents

**Comment by svalaskevicius** [comment]
Hi @wqking,

I've fixed the failing tests + upgraded V8 a minor version again to 3.22.24.5.

Please see this list for the changes:
- e886a96d20b7c3d311872e72e5d82788919fba2c fix tests: store cached class name for object
- 76fe7073402c0ff0847708c8ef920b9fc27e2ee5 return undefined for not existing enum prop
- 3e76cd79a8a3f850e2bf1dd82440fb537860496a fix tests: set hidden prototype flag for V8 methods
- e831406d4ac01290a6caa5e468e74aadcaea1461 improve tests building
- 97e65515a7297e8dabaaf73e9bf96299443e1fef fix tests: include type traits early
- 213d36106cb464f5ba4be14108a002cc332deae2 update nodejs (and in turn v8)
- 072906e119421f2041ba0b13046747018ef8da3d fix tests: propagate item type name
- b63e827e7453fe920948a9a16a0ae8cd26a080c9 fix return type
- c2349e14941bce9ae948a999fe3f811aa04dad52 fix tests crashes
- 4486cc06468d7fdfaacefcb6f620f35d9df6ffa9 fix v8 isolate initialisation
- b501536f547f1273026ac7eeae2146243ccf62ba fix compile errors in tests

Thinking of it - I was only concentrating on the generic cpgf and the v8 tests, and didn't try Lua, Python or SpiderMonkey ones, although they should require only minor updates, if any.

As previously, the git format-patch based diff is available at: https://gist.github.com/svalaskevicius/83d9d1b20319569e67da

Please let me know if you notice any issue with the commits above.

Thanks.

**Comment by svalaskevicius** [comment]
Hi @wqking,

Please can you check the mentioned performance update in commit 2bd14bf0162e5972f26a8ce2f4cba35a84d3c2b5

Currently it requires C++11 features for easier implementation, but could be reimplemented using a similar idea.
(e.g. hashing the type name should work as well, instead of the provided hash_code() )

I haven't completed the full analysis of the improvement, however, after the fix the mentioned method is "invisible" in the callgrind's output, where previously with the same program it took ~3/4 of the program's time. Also the visual improvement is huge (the refresh rate of the program I used to benchmark - examples/widgets.js as it keeps resizing/repainting a rectangle) :)

Please let me know if you see how this could be improved further.

**Comment by wqking** [comment]
Hi,

The commits look good.
Also the performance optimization of meta type lookup is great. Performance was not considered before because it was not the first priority stuff. :-)
Any way, good work, and happy new year.

**Comment by svalaskevicius** [comment]
Thanks! Happy New Year to you as well!

**Pull request merged**
